spring:
  profiles.active: dev
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 16
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB

server:
  port: 8080

springdoc:
  swagger-ui.path: /swagger-ui.html
