-- 임시 시설 스키마 생성 (Space 파트 미구현으로 인한 로컬 프론트 테스트용)
CREATE TABLE IF NOT EXISTS space (
    space_id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(50),
    status VARCHAR(50),
    floor INT,
    area DECIMAL(10,2),
    amenities VARCHAR(255),
    description VARCHAR(255),
    position_x INT,
    position_y INT,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS common_space_detail (
    space_id BIGINT PRIMARY KEY,
    max_capacity INT,
    operating_hours VARCHAR(255),
    usage_fee DECIMAL(10,2),
    is_reservable BOOLEAN
);

CREATE TABLE IF NOT EXISTS space_image (
    space_image_id BIGINT PRIMARY KEY,
    space_id BIGINT,
    image_url VARCHAR(255),
    image_type VARCHAR(50),
    sort_order INT,
    is_thumbnail BOOLEAN,
    deleted_at TIMESTAMP
);

-- ====================================================

-- 데이터 삽입
-- 1. 메인 로비 미팅룸 (예약 가능)
INSERT INTO space (space_id, name, type, status, floor, area, description, position_x, position_y) 
VALUES (1, '메인 로비 미팅룸', 'COMMON', 'AVAILABLE', 1, 30.5, '공용 공간 로비에 위치한 회의실입니다.', 10, 20);

INSERT INTO common_space_detail (space_id, max_capacity, operating_hours, usage_fee, is_reservable) 
VALUES (1, 6, '09:00~22:00', 0, TRUE);

INSERT INTO space_image (space_image_id, space_id, image_url, image_type, sort_order, is_thumbnail) 
VALUES (1, 1, 'https://example.com/meeting1.jpg', 'PHOTO', 1, TRUE);

-- 2. 루프탑 파티룸 (예약 가능)
INSERT INTO space (space_id, name, type, status, floor, area, description, position_x, position_y) 
VALUES (2, '루프탑 파티룸', 'COMMON', 'AVAILABLE', 10, 100.0, '바비큐 및 루프탑 파티룸', 50, 50);

INSERT INTO common_space_detail (space_id, max_capacity, operating_hours, usage_fee, is_reservable) 
VALUES (2, 20, '12:00~23:00', 50000, TRUE);

-- 3. B1 헬스장 (예약 불가 예시용)
INSERT INTO space (space_id, name, type, status, floor, area, description, position_x, position_y) 
VALUES (3, 'B1 헬스장', 'COMMON', 'AVAILABLE', -1, 300.0, '24시간 무인 헬스장', 0, 0);

INSERT INTO common_space_detail (space_id, max_capacity, operating_hours, usage_fee, is_reservable) 
VALUES (3, 50, '00:00~24:00', 0, FALSE);

-- ====================================================

-- 4. 커뮤니티 게시판 샘플 데이터 (posts)
CREATE TABLE IF NOT EXISTS posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(15) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    attachments TEXT NOT NULL,
    links TEXT NOT NULL,
    view_count INT DEFAULT 0 NOT NULL,
    like_count INT DEFAULT 0 NOT NULL,
    comment_count INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

INSERT INTO posts (user_id, category, title, content, attachments, links, view_count, like_count, comment_count, created_at, updated_at) 
VALUES (1, 'NOTICE', '환영합니다! 커뮤니티 게시판입니다.', '입주민 여러분의 소통 공간입니다. 매너 있게 이용해 주세요.', '[]', '[]', 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO posts (user_id, category, title, content, attachments, links, view_count, like_count, comment_count, created_at, updated_at) 
VALUES (2, 'QUESTION', '분리수거 요일이 언제인가요?', '플라스틱이랑 종이 버리는 요일이 헷갈려서요. 아시는 분 답변 부탁드립니다.', '[]', '[]', 5, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO posts (user_id, category, title, content, attachments, links, view_count, like_count, comment_count, created_at, updated_at) 
VALUES (3, 'GATHERING', '오늘 저녁 루프탑에서 맥주 한잔하실 분', '간단하게 치맥하실 분 두 분 정도 모집합니다!', '[]', '[]', 12, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

